import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { GenericFormComponent } from './generic-form/generic-form.component';
import { GenericFormModalComponent } from './generic-form-modal/generic-form-modal.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';
import {
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatRippleModule,
  MatTableModule,
  MatPaginatorModule,
  MatTabsModule,
  MatSortModule,
  MatTooltipModule,
  MatDialogModule,
  MatSelectModule,
  MatDividerModule,
  MatIconModule,
  MatAutocompleteModule,
  MatProgressSpinnerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatCardModule,
  MatChipsModule,
  MatProgressBarModule,
  MatSliderModule,
  MatSidenavModule,
  MatSnackBarModule,
  MatStepperModule,
  MatToolbarModule,
  MatListModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatBottomSheetModule,
  MatExpansionModule,
  MatMenuModule,
  MatTreeModule,
  MatDatepickerModule
} from '@angular/material';
import { AngularEditorModule } from '@kolkov/angular-editor';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { PartialsModule } from '../partials/partials.module';
import { GenericListComponent } from './generic-list/generic-list.component';
import { RouterModule } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard.component';
@NgModule({
  declarations: [
    GenericListComponent,
    GenericFormComponent,
    GenericFormModalComponent,
    DashboardComponent,
  ],
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    ReactiveFormsModule,
    NgbModule,
    PartialsModule,
    AngularEditorModule,
    NgxMatSelectSearchModule,
    // Angular Material Module
    MatDatepickerModule,
    MatCheckboxModule,
    MatTabsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatRippleModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatButtonModule,
    MatTooltipModule,
    MatDialogModule,
    MatSelectModule,
    MatDividerModule,
    MatIconModule,
    MatAutocompleteModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatTreeModule,
    MatNativeDateModule,
    MatRadioModule,
    MatCardModule,
    MatChipsModule,
    MatProgressBarModule,
    MatSliderModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatStepperModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatBottomSheetModule,
    MatExpansionModule
  ],
  entryComponents: [
    GenericFormModalComponent,
  ],
  exports: [
    FormsModule,
    ReactiveFormsModule,
    NgbModule,
    MatTabsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatRippleModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatButtonModule,
    MatTooltipModule,
    MatDialogModule,
    MatSelectModule,
    MatDividerModule,
    MatIconModule,
    MatAutocompleteModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatTreeModule,
    MatNativeDateModule,
    MatRadioModule,
    MatCardModule,
    MatChipsModule,
    MatProgressBarModule,
    MatSliderModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatStepperModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatBottomSheetModule,
    MatExpansionModule,
    MatCheckboxModule,
    // Exported components
    GenericListComponent,
    GenericFormComponent,
    GenericFormModalComponent
  ]
})
export class SharedModule {}
